
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10 Lite
 */
public class AdminPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPanel.class.getName());

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        Admin = new fancyui.FancyButton();
        fancyImage1 = new fancyui.FancyImage();
        fancyLabel2 = new fancyui.FancyLabel();
        logout = new fancyui.FancyButton();
        jSeparator1 = new javax.swing.JSeparator();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyLabel5 = new fancyui.FancyLabel();
        fancyPanel22 = new fancyui.FancyPanel();
        registerbtn9 = new fancyui.FancyButton();
        fancyLabel32 = new fancyui.FancyLabel();
        fancyLabel33 = new fancyui.FancyLabel();
        fancyPanel23 = new fancyui.FancyPanel();
        fancyLabel34 = new fancyui.FancyLabel();
        fancyLabel9 = new fancyui.FancyLabel();
        fancyPanel28 = new fancyui.FancyPanel();
        registerbtn12 = new fancyui.FancyButton();
        fancyLabel41 = new fancyui.FancyLabel();
        fancyLabel42 = new fancyui.FancyLabel();
        fancyPanel29 = new fancyui.FancyPanel();
        fancyLabel43 = new fancyui.FancyLabel();
        fancyLabel11 = new fancyui.FancyLabel();
        fancyPanel30 = new fancyui.FancyPanel();
        registerbtn13 = new fancyui.FancyButton();
        fancyLabel44 = new fancyui.FancyLabel();
        fancyLabel45 = new fancyui.FancyLabel();
        fancyPanel31 = new fancyui.FancyPanel();
        fancyLabel46 = new fancyui.FancyLabel();
        fancyLabel10 = new fancyui.FancyLabel();
        fancyPanel34 = new fancyui.FancyPanel();
        registerbtn15 = new fancyui.FancyButton();
        fancyLabel50 = new fancyui.FancyLabel();
        fancyLabel51 = new fancyui.FancyLabel();
        fancyPanel35 = new fancyui.FancyPanel();
        fancyLabel52 = new fancyui.FancyLabel();
        fancyLabel13 = new fancyui.FancyLabel();
        fancyPanel38 = new fancyui.FancyPanel();
        registerbtn17 = new fancyui.FancyButton();
        fancyLabel56 = new fancyui.FancyLabel();
        fancyLabel57 = new fancyui.FancyLabel();
        fancyPanel39 = new fancyui.FancyPanel();
        fancyLabel58 = new fancyui.FancyLabel();
        fancyLabel47 = new fancyui.FancyLabel();
        fancyPanel40 = new fancyui.FancyPanel();
        registerbtn18 = new fancyui.FancyButton();
        fancyLabel59 = new fancyui.FancyLabel();
        fancyLabel60 = new fancyui.FancyLabel();
        fancyPanel41 = new fancyui.FancyPanel();
        fancyLabel61 = new fancyui.FancyLabel();
        fancyLabel12 = new fancyui.FancyLabel();
        fancyPanel42 = new fancyui.FancyPanel();
        registerbtn19 = new fancyui.FancyButton();
        fancyLabel62 = new fancyui.FancyLabel();
        fancyLabel63 = new fancyui.FancyLabel();
        fancyPanel43 = new fancyui.FancyPanel();
        fancyLabel64 = new fancyui.FancyLabel();
        fancyLabel48 = new fancyui.FancyLabel();
        fancyPanel44 = new fancyui.FancyPanel();
        registerbtn20 = new fancyui.FancyButton();
        fancyLabel65 = new fancyui.FancyLabel();
        fancyLabel66 = new fancyui.FancyLabel();
        fancyPanel45 = new fancyui.FancyPanel();
        fancyLabel67 = new fancyui.FancyLabel();
        fancyLabel49 = new fancyui.FancyLabel();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyLabel6 = new fancyui.FancyLabel();
        fancyLabel7 = new fancyui.FancyLabel();
        fancyPanel24 = new fancyui.FancyPanel();
        fancyPanel25 = new fancyui.FancyPanel();
        fancyPanel26 = new fancyui.FancyPanel();
        fancyButton2 = new fancyui.FancyButton();
        fancyPanel32 = new fancyui.FancyPanel();
        fancyLabel18 = new fancyui.FancyLabel();
        fancyPanel37 = new fancyui.FancyPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyLabel19 = new fancyui.FancyLabel();
        fancyLabel20 = new fancyui.FancyLabel();
        fancyLabel21 = new fancyui.FancyLabel();
        fancyLabel22 = new fancyui.FancyLabel();
        fancyPanel46 = new fancyui.FancyPanel();
        fancyLabel23 = new fancyui.FancyLabel();
        fancyPanel33 = new fancyui.FancyPanel();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyLabel15 = new fancyui.FancyLabel();
        fancyPanel36 = new fancyui.FancyPanel();
        fancyLabel16 = new fancyui.FancyLabel();
        fancyLabel17 = new fancyui.FancyLabel();
        fancyButton3 = new fancyui.FancyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 153));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel2.setCornerRadius(0);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 153));

        Admin.setText("Admin");
        Admin.setBackgroundColor(new java.awt.Color(0, 0, 153));
        Admin.setBorderColor(new java.awt.Color(0, 0, 153));
        Admin.setCornerRadius(10);
        Admin.setDefaultForeground(new java.awt.Color(255, 255, 255));
        Admin.addActionListener(this::AdminActionPerformed);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixlogo.png"))); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        fancyLabel2.setText("Administration");

        logout.setText("Logout");
        logout.setBackgroundColor(new java.awt.Color(0, 0, 153));
        logout.setBorderColor(new java.awt.Color(0, 0, 153));
        logout.setCornerRadius(10);
        logout.setDefaultForeground(new java.awt.Color(255, 255, 255));
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        fancyLabel1.setText("available Courses");
        fancyLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N

        fancyLabel3.setText("Manage the course catalog and view registration overview.");

        fancyPanel3.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setBorderThickness(2.0F);
        fancyPanel3.setGradientEnabled(false);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        fancyLabel5.setText("BSIT 2nd Year — Available Courses (23 total units)");

        fancyPanel22.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel22.setBorderEnabled(true);
        fancyPanel22.setBorderThickness(2.0F);
        fancyPanel22.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel22.setSolidBackgroundEnabled(true);

        registerbtn9.setText("REMOVE");
        registerbtn9.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn9.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn9.addActionListener(this::registerbtn9ActionPerformed);

        fancyLabel32.setText("Qauntitative Methods with Modelling Simulation");

        fancyLabel33.setText("Mon-Face to face - MV 304 8:30–10:30 AM· | Tue- Virtual Classrom 8:00–9:00 AM · 3 units");

        fancyPanel23.setGradientEnabled(false);
        fancyPanel23.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel23.setSolidBackgroundEnabled(true);

        fancyLabel34.setText("MS102");
        fancyLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel23Layout = new javax.swing.GroupLayout(fancyPanel23);
        fancyPanel23.setLayout(fancyPanel23Layout);
        fancyPanel23Layout.setHorizontalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel23Layout.setVerticalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addComponent(fancyLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel9.setText("Mr.Cesar Canlas");

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(registerbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel22Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel28.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel28.setBorderEnabled(true);
        fancyPanel28.setBorderThickness(2.0F);
        fancyPanel28.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel28.setSolidBackgroundEnabled(true);

        registerbtn12.setText("REMOVE");
        registerbtn12.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn12.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn12.addActionListener(this::registerbtn12ActionPerformed);

        fancyLabel41.setText("Sosyedad at Literatura");

        fancyLabel42.setText("Wed-Face to face - MV 304 08:30–10:30 AM· | Th- Virtual Classrom 8:00–9:00 AM · 3 units");

        fancyPanel29.setGradientEnabled(false);
        fancyPanel29.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel29.setSolidBackgroundEnabled(true);

        fancyLabel43.setText("SOSLIT");
        fancyLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel29Layout = new javax.swing.GroupLayout(fancyPanel29);
        fancyPanel29.setLayout(fancyPanel29Layout);
        fancyPanel29Layout.setHorizontalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel29Layout.setVerticalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addComponent(fancyLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel11.setText("Ms.Azucena Lim");

        javax.swing.GroupLayout fancyPanel28Layout = new javax.swing.GroupLayout(fancyPanel28);
        fancyPanel28.setLayout(fancyPanel28Layout);
        fancyPanel28Layout.setHorizontalGroup(
            fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(registerbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel28Layout.setVerticalGroup(
            fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel28Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel28Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel30.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel30.setBorderEnabled(true);
        fancyPanel30.setBorderThickness(2.0F);
        fancyPanel30.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel30.setSolidBackgroundEnabled(true);

        registerbtn13.setText("REMOVE");
        registerbtn13.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn13.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn13.addActionListener(this::registerbtn13ActionPerformed);

        fancyLabel44.setText("Introduction to Human Computer");

        fancyLabel45.setText("Mon-Face to face - MV 304 10:30–12:30 AM· | Tue- Virtual Classrom 9:00–10:00 AM · 3 units");

        fancyPanel31.setGradientEnabled(false);
        fancyPanel31.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel31.setSolidBackgroundEnabled(true);

        fancyLabel46.setText("HCI101");
        fancyLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel31Layout = new javax.swing.GroupLayout(fancyPanel31);
        fancyPanel31.setLayout(fancyPanel31Layout);
        fancyPanel31Layout.setHorizontalGroup(
            fancyPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel31Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel31Layout.setVerticalGroup(
            fancyPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel31Layout.createSequentialGroup()
                .addComponent(fancyLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel10.setText("Ms.Regane Macahibag");

        javax.swing.GroupLayout fancyPanel30Layout = new javax.swing.GroupLayout(fancyPanel30);
        fancyPanel30.setLayout(fancyPanel30Layout);
        fancyPanel30Layout.setHorizontalGroup(
            fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registerbtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel30Layout.setVerticalGroup(
            fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel30Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel30Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel34.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel34.setBorderEnabled(true);
        fancyPanel34.setBorderThickness(2.0F);
        fancyPanel34.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel34.setSolidBackgroundEnabled(true);

        registerbtn15.setText("REMOVE");
        registerbtn15.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn15.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn15.addActionListener(this::registerbtn15ActionPerformed);

        fancyLabel50.setText("Data Structures and Algorithms");

        fancyLabel51.setText("Fri-Face to face - MV 304 6:00–8:00 AM· | Sat- Virtual Classrom 6:00–8:00 AM · 3 units");

        fancyPanel35.setGradientEnabled(false);
        fancyPanel35.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel35.setSolidBackgroundEnabled(true);

        fancyLabel52.setText("CC104");
        fancyLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel35Layout = new javax.swing.GroupLayout(fancyPanel35);
        fancyPanel35.setLayout(fancyPanel35Layout);
        fancyPanel35Layout.setHorizontalGroup(
            fancyPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel35Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel35Layout.setVerticalGroup(
            fancyPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel35Layout.createSequentialGroup()
                .addComponent(fancyLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel13.setText("Mr.Jayboy Colo");

        javax.swing.GroupLayout fancyPanel34Layout = new javax.swing.GroupLayout(fancyPanel34);
        fancyPanel34.setLayout(fancyPanel34Layout);
        fancyPanel34Layout.setHorizontalGroup(
            fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(registerbtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel34Layout.setVerticalGroup(
            fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel34Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel38.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel38.setBorderEnabled(true);
        fancyPanel38.setBorderThickness(2.0F);
        fancyPanel38.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel38.setSolidBackgroundEnabled(true);

        registerbtn17.setText("REMOVE");
        registerbtn17.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn17.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn17.addActionListener(this::registerbtn17ActionPerformed);

        fancyLabel56.setText("Integrative Programming and Technologies");

        fancyLabel57.setText("Fri-Face to face - MV 304 8:30–10:30 AM· | Sat- Virtual Classrom 8:00–10:00 AM · 3 units");

        fancyPanel39.setGradientEnabled(false);
        fancyPanel39.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel39.setSolidBackgroundEnabled(true);

        fancyLabel58.setText("IPT101");
        fancyLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel39Layout = new javax.swing.GroupLayout(fancyPanel39);
        fancyPanel39.setLayout(fancyPanel39Layout);
        fancyPanel39Layout.setHorizontalGroup(
            fancyPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel39Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        fancyPanel39Layout.setVerticalGroup(
            fancyPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel39Layout.createSequentialGroup()
                .addComponent(fancyLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel47.setText("Mr.Romel Cabiling");

        javax.swing.GroupLayout fancyPanel38Layout = new javax.swing.GroupLayout(fancyPanel38);
        fancyPanel38.setLayout(fancyPanel38Layout);
        fancyPanel38Layout.setHorizontalGroup(
            fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(registerbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel38Layout.setVerticalGroup(
            fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel38Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel38Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel40.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel40.setBorderEnabled(true);
        fancyPanel40.setBorderThickness(2.0F);
        fancyPanel40.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel40.setSolidBackgroundEnabled(true);

        registerbtn18.setText("REMOVE");
        registerbtn18.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn18.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn18.addActionListener(this::registerbtn18ActionPerformed);

        fancyLabel59.setText("Individual and Dual Sports");

        fancyLabel60.setText("Wed-Face to face - MV 304  10:30–12:30 AM · 2units");

        fancyPanel41.setGradientEnabled(false);
        fancyPanel41.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel41.setSolidBackgroundEnabled(true);

        fancyLabel61.setText("PE3");
        fancyLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel41Layout = new javax.swing.GroupLayout(fancyPanel41);
        fancyPanel41.setLayout(fancyPanel41Layout);
        fancyPanel41Layout.setHorizontalGroup(
            fancyPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel41Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        fancyPanel41Layout.setVerticalGroup(
            fancyPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel41Layout.createSequentialGroup()
                .addComponent(fancyLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel12.setText("Ms.Rose Ann");

        javax.swing.GroupLayout fancyPanel40Layout = new javax.swing.GroupLayout(fancyPanel40);
        fancyPanel40.setLayout(fancyPanel40Layout);
        fancyPanel40Layout.setHorizontalGroup(
            fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(registerbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel40Layout.setVerticalGroup(
            fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel40Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel40Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel42.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel42.setBorderEnabled(true);
        fancyPanel42.setBorderThickness(2.0F);
        fancyPanel42.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel42.setSolidBackgroundEnabled(true);

        registerbtn19.setText("REMOVE");
        registerbtn19.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn19.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn19.addActionListener(this::registerbtn19ActionPerformed);

        fancyLabel62.setText("IT Elective 1 (Web Fundamental)");

        fancyLabel63.setText("Fri-Face to face - MV 304 10:30–12:30 AM· | Sat- Virtual Classrom 10:00–12:00 AM · 3 units");

        fancyPanel43.setGradientEnabled(false);
        fancyPanel43.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel43.setSolidBackgroundEnabled(true);

        fancyLabel64.setText("ITE1");
        fancyLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel43Layout = new javax.swing.GroupLayout(fancyPanel43);
        fancyPanel43.setLayout(fancyPanel43Layout);
        fancyPanel43Layout.setHorizontalGroup(
            fancyPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel43Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        fancyPanel43Layout.setVerticalGroup(
            fancyPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel43Layout.createSequentialGroup()
                .addComponent(fancyLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel48.setText("Unknown");

        javax.swing.GroupLayout fancyPanel42Layout = new javax.swing.GroupLayout(fancyPanel42);
        fancyPanel42.setLayout(fancyPanel42Layout);
        fancyPanel42Layout.setHorizontalGroup(
            fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(registerbtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel42Layout.setVerticalGroup(
            fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel42Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel42Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel44.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel44.setBorderEnabled(true);
        fancyPanel44.setBorderThickness(2.0F);
        fancyPanel44.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel44.setSolidBackgroundEnabled(true);

        registerbtn20.setText("REMOVE");
        registerbtn20.setBackgroundColor(new java.awt.Color(255, 51, 51));
        registerbtn20.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn20.addActionListener(this::registerbtn20ActionPerformed);

        fancyLabel65.setText("Networking 1");

        fancyLabel66.setText("Mon-Face to face - MV 304 6:00–08:00 AM· | Tue- Virtual Classrom 7:00–8:00 AM · 3 units");

        fancyPanel45.setGradientEnabled(false);
        fancyPanel45.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel45.setSolidBackgroundEnabled(true);

        fancyLabel67.setText("NET 101");
        fancyLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel45Layout = new javax.swing.GroupLayout(fancyPanel45);
        fancyPanel45.setLayout(fancyPanel45Layout);
        fancyPanel45Layout.setHorizontalGroup(
            fancyPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel45Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel45Layout.setVerticalGroup(
            fancyPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel45Layout.createSequentialGroup()
                .addComponent(fancyLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel49.setText("Mr.Aldrine De Guzman");

        javax.swing.GroupLayout fancyPanel44Layout = new javax.swing.GroupLayout(fancyPanel44);
        fancyPanel44.setLayout(fancyPanel44Layout);
        fancyPanel44Layout.setHorizontalGroup(
            fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(registerbtn20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel44Layout.setVerticalGroup(
            fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel44Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel44Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbtn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fancyPanel45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyLabel4.setText("CODE");

        fancyLabel6.setText("COURSE NAME");

        fancyLabel7.setText("UNITS");

        fancyPanel24.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel24.setBorderEnabled(true);
        fancyPanel24.setCornerRadius(7);
        fancyPanel24.setGradientEnabled(false);
        fancyPanel24.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel24.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel24.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel24.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel24Layout = new javax.swing.GroupLayout(fancyPanel24);
        fancyPanel24.setLayout(fancyPanel24Layout);
        fancyPanel24Layout.setHorizontalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        fancyPanel24Layout.setVerticalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        fancyPanel25.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel25.setBorderEnabled(true);
        fancyPanel25.setCornerRadius(7);
        fancyPanel25.setGradientEnabled(false);
        fancyPanel25.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel25.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel25.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel25.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel25Layout = new javax.swing.GroupLayout(fancyPanel25);
        fancyPanel25.setLayout(fancyPanel25Layout);
        fancyPanel25Layout.setHorizontalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        fancyPanel25Layout.setVerticalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        fancyPanel26.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel26.setBorderEnabled(true);
        fancyPanel26.setCornerRadius(7);
        fancyPanel26.setGradientEnabled(false);
        fancyPanel26.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel26.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel26.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel26.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel26Layout = new javax.swing.GroupLayout(fancyPanel26);
        fancyPanel26.setLayout(fancyPanel26Layout);
        fancyPanel26Layout.setHorizontalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        fancyPanel26Layout.setVerticalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        fancyButton2.setText("Add Courses");
        fancyButton2.setBackgroundColor(new java.awt.Color(0, 0, 0));
        fancyButton2.setDefaultForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fancyPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addComponent(fancyPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(fancyPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        fancyPanel32.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel32.setBorderEnabled(true);
        fancyPanel32.setCornerRadius(7);
        fancyPanel32.setGradientEnabled(false);
        fancyPanel32.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel32.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel32.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel32.setSolidBackgroundEnabled(true);

        fancyLabel18.setText("Currently Enrolled Students");

        fancyPanel37.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel37.setBorderEnabled(true);
        fancyPanel37.setCornerRadius(7);
        fancyPanel37.setGradientEnabled(false);
        fancyPanel37.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel37.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel37.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel37.setSolidBackgroundEnabled(true);

        fancyPanel4.setBottomRightRadius(5);
        fancyPanel4.setCornerRadius(5);
        fancyPanel4.setGradientEnd(new java.awt.Color(0, 102, 255));
        fancyPanel4.setGradientStart(new java.awt.Color(51, 153, 255));

        fancyLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        fancyLabel20.setText("ST");
        fancyLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fancyLabel21.setText("Student");

        fancyLabel22.setText("2024-10234");

        fancyPanel46.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel46.setBorderEnabled(true);
        fancyPanel46.setCornerRadius(7);
        fancyPanel46.setGradientEnabled(false);
        fancyPanel46.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel46.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel46.setSolidBackgroundColor(new java.awt.Color(0, 0, 0));
        fancyPanel46.setSolidBackgroundEnabled(true);

        fancyLabel23.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel23.setText("3 Units");

        javax.swing.GroupLayout fancyPanel46Layout = new javax.swing.GroupLayout(fancyPanel46);
        fancyPanel46.setLayout(fancyPanel46Layout);
        fancyPanel46Layout.setHorizontalGroup(
            fancyPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel46Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(fancyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        fancyPanel46Layout.setVerticalGroup(
            fancyPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel46Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(fancyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout fancyPanel37Layout = new javax.swing.GroupLayout(fancyPanel37);
        fancyPanel37.setLayout(fancyPanel37Layout);
        fancyPanel37Layout.setHorizontalGroup(
            fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 538, Short.MAX_VALUE)
                .addComponent(fancyPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel37Layout.setVerticalGroup(
            fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel37Layout.createSequentialGroup()
                        .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fancyPanel37Layout.createSequentialGroup()
                        .addComponent(fancyPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout fancyPanel32Layout = new javax.swing.GroupLayout(fancyPanel32);
        fancyPanel32.setLayout(fancyPanel32Layout);
        fancyPanel32Layout.setHorizontalGroup(
            fancyPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel32Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(fancyPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel32Layout.setVerticalGroup(
            fancyPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        fancyPanel33.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel33.setBorderEnabled(true);
        fancyPanel33.setCornerRadius(7);
        fancyPanel33.setGradientEnabled(false);
        fancyPanel33.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel33.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel33.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel33.setSolidBackgroundEnabled(true);

        fancyLabel14.setText("COURSE OFFERED");
        fancyLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fancyLabel15.setText("9");
        fancyLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        javax.swing.GroupLayout fancyPanel33Layout = new javax.swing.GroupLayout(fancyPanel33);
        fancyPanel33.setLayout(fancyPanel33Layout);
        fancyPanel33Layout.setHorizontalGroup(
            fancyPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel33Layout.createSequentialGroup()
                .addGroup(fancyPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel33Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel33Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        fancyPanel33Layout.setVerticalGroup(
            fancyPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel33Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        fancyPanel36.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel36.setBorderEnabled(true);
        fancyPanel36.setCornerRadius(7);
        fancyPanel36.setGradientEnabled(false);
        fancyPanel36.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel36.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel36.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel36.setSolidBackgroundEnabled(true);

        fancyLabel16.setText("REGISTERED STUDENTS");
        fancyLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fancyLabel17.setText("2");
        fancyLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        javax.swing.GroupLayout fancyPanel36Layout = new javax.swing.GroupLayout(fancyPanel36);
        fancyPanel36.setLayout(fancyPanel36Layout);
        fancyPanel36Layout.setHorizontalGroup(
            fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel36Layout.createSequentialGroup()
                .addGroup(fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel36Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(fancyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel36Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        fancyPanel36Layout.setVerticalGroup(
            fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel36Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        fancyButton3.setText("AY 2026–2027 · 1st Semester");

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fancyPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGap(0, 29, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(fancyPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel1Layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(fancyPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(742, Short.MAX_VALUE)))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel1Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(fancyPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(607, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
       
    }//GEN-LAST:event_AdminActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void registerbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn9ActionPerformed

    private void registerbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn19ActionPerformed

    private void registerbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn17ActionPerformed

    private void registerbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn15ActionPerformed

    private void registerbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn18ActionPerformed

    private void registerbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn12ActionPerformed

    private void registerbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn13ActionPerformed

    private void registerbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton Admin;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyButton fancyButton3;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel15;
    private fancyui.FancyLabel fancyLabel16;
    private fancyui.FancyLabel fancyLabel17;
    private fancyui.FancyLabel fancyLabel18;
    private fancyui.FancyLabel fancyLabel19;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel20;
    private fancyui.FancyLabel fancyLabel21;
    private fancyui.FancyLabel fancyLabel22;
    private fancyui.FancyLabel fancyLabel23;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel32;
    private fancyui.FancyLabel fancyLabel33;
    private fancyui.FancyLabel fancyLabel34;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel41;
    private fancyui.FancyLabel fancyLabel42;
    private fancyui.FancyLabel fancyLabel43;
    private fancyui.FancyLabel fancyLabel44;
    private fancyui.FancyLabel fancyLabel45;
    private fancyui.FancyLabel fancyLabel46;
    private fancyui.FancyLabel fancyLabel47;
    private fancyui.FancyLabel fancyLabel48;
    private fancyui.FancyLabel fancyLabel49;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel50;
    private fancyui.FancyLabel fancyLabel51;
    private fancyui.FancyLabel fancyLabel52;
    private fancyui.FancyLabel fancyLabel56;
    private fancyui.FancyLabel fancyLabel57;
    private fancyui.FancyLabel fancyLabel58;
    private fancyui.FancyLabel fancyLabel59;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel60;
    private fancyui.FancyLabel fancyLabel61;
    private fancyui.FancyLabel fancyLabel62;
    private fancyui.FancyLabel fancyLabel63;
    private fancyui.FancyLabel fancyLabel64;
    private fancyui.FancyLabel fancyLabel65;
    private fancyui.FancyLabel fancyLabel66;
    private fancyui.FancyLabel fancyLabel67;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel23;
    private fancyui.FancyPanel fancyPanel24;
    private fancyui.FancyPanel fancyPanel25;
    private fancyui.FancyPanel fancyPanel26;
    private fancyui.FancyPanel fancyPanel28;
    private fancyui.FancyPanel fancyPanel29;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel30;
    private fancyui.FancyPanel fancyPanel31;
    private fancyui.FancyPanel fancyPanel32;
    private fancyui.FancyPanel fancyPanel33;
    private fancyui.FancyPanel fancyPanel34;
    private fancyui.FancyPanel fancyPanel35;
    private fancyui.FancyPanel fancyPanel36;
    private fancyui.FancyPanel fancyPanel37;
    private fancyui.FancyPanel fancyPanel38;
    private fancyui.FancyPanel fancyPanel39;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel40;
    private fancyui.FancyPanel fancyPanel41;
    private fancyui.FancyPanel fancyPanel42;
    private fancyui.FancyPanel fancyPanel43;
    private fancyui.FancyPanel fancyPanel44;
    private fancyui.FancyPanel fancyPanel45;
    private fancyui.FancyPanel fancyPanel46;
    private javax.swing.JSeparator jSeparator1;
    private fancyui.FancyButton logout;
    private fancyui.FancyButton registerbtn12;
    private fancyui.FancyButton registerbtn13;
    private fancyui.FancyButton registerbtn15;
    private fancyui.FancyButton registerbtn17;
    private fancyui.FancyButton registerbtn18;
    private fancyui.FancyButton registerbtn19;
    private fancyui.FancyButton registerbtn20;
    private fancyui.FancyButton registerbtn9;
    // End of variables declaration//GEN-END:variables
}
