
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Windows 10 Lite
 */
public class Admin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        user = new fancyui.FancyTextField();
        pass = new fancyui.FancyPasswordField();
        loginbtn = new fancyui.FancyButton();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyButton1 = new fancyui.FancyButton();
        admin = new fancyui.FancyButton();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyImage1 = new fancyui.FancyImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 153));

        fancyPanel2.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setBorderThickness(2.0F);
        fancyPanel2.setCornerRadius(20);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 153));

        user.setPlaceholder("Admin ID");

        loginbtn.setText("Login");
        loginbtn.setBorderThickness(2.0F);
        loginbtn.setCornerRadius(6);
        loginbtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setGradientEnabled(true);
        loginbtn.setGradientEnd(new java.awt.Color(0, 0, 0));
        loginbtn.setGradientStart(new java.awt.Color(0, 0, 153));
        loginbtn.setHoverForeground(java.awt.Color.white);
        loginbtn.addActionListener(this::loginbtnActionPerformed);

        fancyPanel3.setGradientEnabled(false);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        fancyButton1.setText("Student");
        fancyButton1.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyButton1.setHoverBackground(new java.awt.Color(0, 0, 0));
        fancyButton1.setHoverForeground(java.awt.Color.white);

        admin.setText("Admin");
        admin.setBorderColor(new java.awt.Color(255, 255, 255));
        admin.setHoverBackground(new java.awt.Color(0, 0, 0));
        admin.setHoverForeground(java.awt.Color.white);

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel1.setText("Please Enter.");

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixbglet.JPG"))); // NOI18N

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String username = user.getText();
        String password = pass.getText();

        String role = new DBConn().login(username, password);
         if (role.equalsIgnoreCase("admin")){
            JOptionPane.showMessageDialog(this, "Login Success! Welcome Admin");
            new AdminPanel().setVisible(true);
            this.dispose();
            
        }else if(role.equalsIgnoreCase("student")){
            JOptionPane.showMessageDialog(this, "Access Denied! This login is for ADMIN ONLY!");
 
            
        }else{
            JOptionPane.showMessageDialog(this, "Invalid username or password!");
        }

       // if (success) {
      //      JOptionPane.showMessageDialog(this, "Login Success");
        //    new AdminPanel().setVisible(true);
       //     this.dispose();
      //  } else {
       //     JOptionPane.showMessageDialog(this, "Login Failed");
      //  }
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton admin;
    private fancyui.FancyButton fancyButton1;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyButton loginbtn;
    private fancyui.FancyPasswordField pass;
    private fancyui.FancyTextField user;
    // End of variables declaration//GEN-END:variables
}
