
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Windows 10 Lite
 */
public class Dashboard extends javax.swing.JFrame {
    
    

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    private String loggedInStudentID;
    public Dashboard() {
        this("");
        initComponents();
    } 
    public Dashboard(String studentID) {
        initComponents();
        
        this.loggedInStudentID = studentID;
        
        setLocationRelativeTo(null);
        addRegisterModal.setLocationRelativeTo(null);
        studenttable.setModel(new DBConn().getAllInfo());
        
//    new DBConn().getAllInfo(studenttable);
////        String[] headers = {"Student ID", "Code", "Subject", "Schedule", "Teacher", "Status"};
////
////        DefaultTableModel model = new DefaultTableModel(headers, 0);
////
////       model.addRow(new String[]{"s25010010","NET101", "Networking", "Monday", "Aldrine De Guzman", "Active"});
////        model.addRow(new String[]{"s25010010","HCI1", "Human Interaction", "Monday", "Regane Macahibag", "Active"});
////        
////       studenttable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRegisterModal = new javax.swing.JDialog();
        fancyPanel9 = new fancyui.FancyPanel();
        fancyPanel5 = new fancyui.FancyPanel();
        fancyImage2 = new fancyui.FancyImage();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyPanel6 = new fancyui.FancyPanel();
        code = new fancyui.FancyTextField();
        studentID = new fancyui.FancyTextField();
        schedule = new fancyui.FancyTextField();
        subject = new javax.swing.JComboBox<>();
        teacher = new javax.swing.JComboBox<>();
        active = new javax.swing.JCheckBox();
        register = new fancyui.FancyButton();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        dashboard = new fancyui.FancyButton();
        fancyImage1 = new fancyui.FancyImage();
        fancyLabel2 = new fancyui.FancyLabel();
        mycourses = new fancyui.FancyButton();
        courses = new fancyui.FancyButton();
        profile = new fancyui.FancyButton();
        logout = new fancyui.FancyButton();
        jSeparator1 = new javax.swing.JSeparator();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyLabel6 = new fancyui.FancyLabel();
        fancyLabel7 = new fancyui.FancyLabel();
        fancyLabel8 = new fancyui.FancyLabel();
        fancyLabel9 = new fancyui.FancyLabel();
        fancyLabel10 = new fancyui.FancyLabel();
        fancyLabel11 = new fancyui.FancyLabel();
        fancyLabel12 = new fancyui.FancyLabel();
        fancyLabel13 = new fancyui.FancyLabel();
        fancyPanel4 = new fancyui.FancyPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studenttable = new fancyui.FancyTable();
        registerbtn = new fancyui.FancyButton();
        fancyButton2 = new fancyui.FancyButton();
        fancyPanel7 = new fancyui.FancyPanel();
        fancyPanel8 = new fancyui.FancyPanel();
        jLabel2 = new javax.swing.JLabel();
        fancyLabel5 = new fancyui.FancyLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        addRegisterModal.setResizable(false);
        addRegisterModal.setSize(new java.awt.Dimension(700, 500));
        addRegisterModal.setType(java.awt.Window.Type.POPUP);

        fancyPanel9.setCornerRadius(0);
        fancyPanel9.setGradientEnabled(false);
        fancyPanel9.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel9.setGradientStart(new java.awt.Color(0, 0, 153));
        fancyPanel9.setSolidBackgroundColor(new java.awt.Color(0, 0, 102));
        fancyPanel9.setSolidBackgroundEnabled(true);

        fancyPanel5.setBorderEnabled(true);
        fancyPanel5.setCornerRadius(15);
        fancyPanel5.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel5.setGradientStart(new java.awt.Color(0, 0, 153));

        fancyImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixlogo.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel5Layout = new javax.swing.GroupLayout(fancyPanel5);
        fancyPanel5.setLayout(fancyPanel5Layout);
        fancyPanel5Layout.setHorizontalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        fancyPanel5Layout.setVerticalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel4.setText("ENTER COURSES");
        fancyLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        fancyPanel6.setBorderEnabled(true);
        fancyPanel6.setBorderThickness(2.0F);
        fancyPanel6.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel6.setGradientStart(new java.awt.Color(0, 0, 153));

        code.setPlaceholder("Code");

        studentID.setPlaceholder("Student_ID");

        schedule.setPlaceholder("Schedule");
        schedule.addActionListener(this::scheduleActionPerformed);

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Subject", "Networking 1", "Quantitative Methods with Modelling Simulation", "Introduction to Human Computer", "Sosyedad at Literatura", "Individual and Dual Sports", "Data Structures and Algorithms", "Integrative Programming and Technologies", "IT Elective 1" }));

        teacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Teacher", "Mr.Aldrine De Guzman (NET101)", "Mr.Cesar Canlas (MS102)", "Ms.Regane Macahibag (HCI101)", "Ms.Azucena S. Lim (SOSLIT)", "Mr.Romel Cabiling (IPT101)", "Mr.Jayboy Colo (CC104)", "Ms.Rose Ann (PE3)", " " }));

        active.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        active.setForeground(new java.awt.Color(255, 255, 255));
        active.setText("Active");

        register.setText("Register");
        register.addActionListener(this::registerActionPerformed);

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(active)
                    .addComponent(schedule, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(studentID, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacher, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subject, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(active)
                .addGap(18, 18, 18)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel9Layout = new javax.swing.GroupLayout(fancyPanel9);
        fancyPanel9.setLayout(fancyPanel9Layout);
        fancyPanel9Layout.setHorizontalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addComponent(fancyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel9Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        fancyPanel9Layout.setVerticalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout addRegisterModalLayout = new javax.swing.GroupLayout(addRegisterModal.getContentPane());
        addRegisterModal.getContentPane().setLayout(addRegisterModalLayout);
        addRegisterModalLayout.setHorizontalGroup(
            addRegisterModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addRegisterModalLayout.setVerticalGroup(
            addRegisterModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fancyPanel9.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 153));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel2.setCornerRadius(0);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 153));

        dashboard.setText("Dashboard");
        dashboard.setBackgroundColor(new java.awt.Color(0, 0, 153));
        dashboard.setBorderColor(new java.awt.Color(0, 0, 153));
        dashboard.setCornerRadius(10);
        dashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixlogo.png"))); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        fancyLabel2.setText("Menu");

        mycourses.setText("My Courses");
        mycourses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        mycourses.setBorderColor(new java.awt.Color(0, 0, 153));
        mycourses.setCornerRadius(10);
        mycourses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        mycourses.addActionListener(this::mycoursesActionPerformed);

        courses.setText("Courses");
        courses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        courses.setBorderColor(new java.awt.Color(0, 0, 153));
        courses.setCornerRadius(10);
        courses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        courses.addActionListener(this::coursesActionPerformed);

        profile.setText("Profile");
        profile.setBackgroundColor(new java.awt.Color(0, 0, 153));
        profile.setBorderColor(new java.awt.Color(0, 0, 153));
        profile.setCornerRadius(10);
        profile.setDefaultForeground(new java.awt.Color(255, 255, 255));
        profile.addActionListener(this::profileActionPerformed);

        logout.setText("Logout");
        logout.setBackgroundColor(new java.awt.Color(0, 0, 153));
        logout.setBorderColor(new java.awt.Color(0, 0, 153));
        logout.setCornerRadius(10);
        logout.setDefaultForeground(new java.awt.Color(255, 255, 255));
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mycourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mycourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        fancyLabel1.setText("Dashboard");
        fancyLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N

        fancyLabel3.setText("Welcome back — here's your registration status.");

        fancyPanel3.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel3.setGradientStart(new java.awt.Color(51, 0, 153));

        fancyLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel6.setText("WELCOME, STUDENT");
        fancyLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        fancyLabel7.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel7.setText("BSIT 2nd Year · Section IT-201 · Student No. 2024-10234");

        fancyLabel8.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel8.setText("0");
        fancyLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        fancyLabel9.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel9.setText("Units Enrolled");
        fancyLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fancyLabel10.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel10.setText("0");
        fancyLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        fancyLabel11.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel11.setText("27");
        fancyLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        fancyLabel12.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel12.setText("Subject");
        fancyLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fancyLabel13.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel13.setText("Max load");
        fancyLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fancyPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(fancyPanel3Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)))
                        .addGap(18, 18, 18)
                        .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setBorderThickness(2.0F);
        fancyPanel4.setCornerRadius(20);
        fancyPanel4.setGradientEnabled(false);
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel4.setSolidBackgroundEnabled(true);

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"s250100006", "MS102", "Mathematics", "Monday", "Cesar Canlas", "Active"},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Code", "Subject", "Schedule", "Teacher", "Status"
            }
        ));
        studenttable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studenttable.setGradientEnd(new java.awt.Color(0, 0, 0));
        studenttable.setGradientStart(new java.awt.Color(0, 0, 153));
        studenttable.setGridEnabled(false);
        studenttable.setGridLineColor(new java.awt.Color(204, 204, 204));
        studenttable.setHeaderBackground(new java.awt.Color(0, 0, 153));
        studenttable.setHeaderForeground(new java.awt.Color(255, 255, 255));
        studenttable.setOddRowColor(new java.awt.Color(0, 0, 153));
        jScrollPane2.setViewportView(studenttable);

        registerbtn.setText("My Register Courses");
        registerbtn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        registerbtn.setBorderColor(new java.awt.Color(255, 255, 255));
        registerbtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn.addActionListener(this::registerbtnActionPerformed);

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        fancyButton2.setText("AY 2026–2027 · 1st Semester");

        fancyPanel7.setBorderEnabled(true);
        fancyPanel7.setGradientEnd(new java.awt.Color(0, 153, 255));
        fancyPanel7.setGradientStart(new java.awt.Color(0, 102, 153));
        fancyPanel7.setSolidBackgroundEnabled(true);

        fancyPanel8.setBorderEnabled(true);
        fancyPanel8.setCornerRadius(360);
        fancyPanel8.setSolidBackgroundEnabled(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("0");

        fancyLabel5.setText("of 27 units");

        javax.swing.GroupLayout fancyPanel8Layout = new javax.swing.GroupLayout(fancyPanel8);
        fancyPanel8.setLayout(fancyPanel8Layout);
        fancyPanel8Layout.setHorizontalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel8Layout.createSequentialGroup()
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        fancyPanel8Layout.setVerticalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        jLabel1.setText("UNIT LOAD METER");

        jRadioButton1.setText("Room for more Courses");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        javax.swing.GroupLayout fancyPanel7Layout = new javax.swing.GroupLayout(fancyPanel7);
        fancyPanel7.setLayout(fancyPanel7Layout);
        fancyPanel7Layout.setHorizontalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addGroup(fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel7Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addGroup(fancyPanel7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))))
                    .addGroup(fancyPanel7Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(fancyPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        fancyPanel7Layout.setVerticalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(fancyPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(fancyPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycoursesActionPerformed
         new MyCourses().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_mycoursesActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
      new Profile().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
       
        new Courses(loggedInStudentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
    
        addRegisterModal.setLocationRelativeTo(this);
        addRegisterModal.setVisible(true);
        
    String studentIDValue = studentID.getText();
    String codeValue = code.getText();
    String scheduleValue = schedule.getText();

    String subjectValue = subject.getSelectedItem().toString();
    String teacherValue = teacher.getSelectedItem().toString();

    String statusValue;

    if (active.isSelected()) {
        statusValue = "Active";
    } else {
        statusValue = "Inactive";
    }

    if (studentIDValue.isEmpty() ||
        codeValue.isEmpty() ||
        scheduleValue.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please complete all required fields."
        );

        return;
    }

    DBConn db = new DBConn();

    boolean saved = db.saveCourse(
            studentIDValue,
            codeValue,
            subjectValue,
            scheduleValue,
            teacherValue,
            statusValue
    );

    if (saved) {

        JOptionPane.showMessageDialog(
                this,
                "Course registered successfully!"
        );

        addRegisterModal.setVisible(false);

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to save course."
        );
    }
//    String studentID = JOptionPane.showInputDialog(this, "Enter Student ID");
//    String code = JOptionPane.showInputDialog(this, "Enter Code");
//    String subject = JOptionPane.showInputDialog(this, "Enter Subject");
//    String schedule = JOptionPane.showInputDialog(this, "Enter Schedule");
//    String teacher = JOptionPane.showInputDialog(this, "Enter Teacher");
//    DefaultTableModel model = (DefaultTableModel) studenttable.getModel();
//    model.addRow(new String[] {studentID, code, subject, schedule, teacher, "Active"});
//
//    addRegisterModal.hide();
//    JOptionPane.showMessageDialog(this, "Register Successfully!");

        
    }//GEN-LAST:event_registerbtnActionPerformed

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        
    String studentIDValue = studentID.getText().trim();
    String codeValue = code.getText().trim();
    String scheduleValue = schedule.getText().trim();
    String subjectValue = subject.getSelectedItem().toString();
    String teacherValue = teacher.getSelectedItem().toString();

    String statusValue;

    if (active.isSelected()) {
        statusValue = "Active";
    } else {
        statusValue = "Inactive";
    }
if (studentIDValue.isEmpty() ||
        codeValue.isEmpty() ||
        scheduleValue.isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please complete all required fields."
        );

        return;
    }

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) studenttable.getModel();

    model.addRow(new Object[]{
        studentIDValue,
        codeValue,
        subjectValue,
        scheduleValue,
        teacherValue,
        statusValue
    });

    JOptionPane.showMessageDialog(
        this,
        "Course registered successfully!"
    );

    addRegisterModal.setVisible(false);

    }//GEN-LAST:event_registerActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox active;
    private javax.swing.JDialog addRegisterModal;
    private fancyui.FancyTextField code;
    private fancyui.FancyButton courses;
    private fancyui.FancyButton dashboard;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyLabel fancyLabel8;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel5;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyPanel fancyPanel7;
    private fancyui.FancyPanel fancyPanel8;
    private fancyui.FancyPanel fancyPanel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private fancyui.FancyButton logout;
    private fancyui.FancyButton mycourses;
    private fancyui.FancyButton profile;
    private fancyui.FancyButton register;
    private fancyui.FancyButton registerbtn;
    private fancyui.FancyTextField schedule;
    private fancyui.FancyTextField studentID;
    private fancyui.FancyTable studenttable;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JComboBox<String> teacher;
    // End of variables declaration//GEN-END:variables

    private void If(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
