
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10 Lite
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyPanel23 = new fancyui.FancyPanel();
        fancyLabel10 = new fancyui.FancyLabel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        dashboard = new fancyui.FancyButton();
        fancyImage1 = new fancyui.FancyImage();
        fancyLabel2 = new fancyui.FancyLabel();
        mycourses = new fancyui.FancyButton();
        courses = new fancyui.FancyButton();
        profile = new fancyui.FancyButton();
        logout = new fancyui.FancyButton();
        jSeparator1 = new javax.swing.JSeparator();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyLabel5 = new fancyui.FancyLabel();
        fancyLabel6 = new fancyui.FancyLabel();
        fancyPanel15 = new fancyui.FancyPanel();
        fancyLabel7 = new fancyui.FancyLabel();
        fancyLabel13 = new fancyui.FancyLabel();
        fancyPanel21 = new fancyui.FancyPanel();
        fancyLabel8 = new fancyui.FancyLabel();
        fancyLabel12 = new fancyui.FancyLabel();
        fancyPanel22 = new fancyui.FancyPanel();
        fancyLabel9 = new fancyui.FancyLabel();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyPanel24 = new fancyui.FancyPanel();
        fancyLabel11 = new fancyui.FancyLabel();
        fancyLabel15 = new fancyui.FancyLabel();
        fancyButton2 = new fancyui.FancyButton();

        fancyPanel23.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel23.setBorderEnabled(true);
        fancyPanel23.setCornerRadius(7);
        fancyPanel23.setGradientEnabled(false);
        fancyPanel23.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel23.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel23.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel23.setSolidBackgroundEnabled(true);

        fancyLabel10.setText("STUDENT NUMBER");

        javax.swing.GroupLayout fancyPanel23Layout = new javax.swing.GroupLayout(fancyPanel23);
        fancyPanel23.setLayout(fancyPanel23Layout);
        fancyPanel23Layout.setHorizontalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        fancyPanel23Layout.setVerticalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 153));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel2.setCornerRadius(0);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 153));

        dashboard.setText("Dashboard");
        dashboard.setBackgroundColor(new java.awt.Color(0, 0, 153));
        dashboard.setBorderColor(new java.awt.Color(0, 0, 153));
        dashboard.setCornerRadius(10);
        dashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));
        dashboard.addActionListener(this::dashboardActionPerformed);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixlogo.png"))); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        fancyLabel2.setText("Menu");

        mycourses.setText("My Courses");
        mycourses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        mycourses.setBorderColor(new java.awt.Color(0, 0, 153));
        mycourses.setCornerRadius(10);
        mycourses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        mycourses.addActionListener(this::mycoursesActionPerformed);

        courses.setText("Courses");
        courses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        courses.setBorderColor(new java.awt.Color(0, 0, 153));
        courses.setCornerRadius(10);
        courses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        courses.addActionListener(this::coursesActionPerformed);

        profile.setText("Profile");
        profile.setBackgroundColor(new java.awt.Color(0, 0, 153));
        profile.setBorderColor(new java.awt.Color(0, 0, 153));
        profile.setCornerRadius(10);
        profile.setDefaultForeground(new java.awt.Color(255, 255, 255));
        profile.addActionListener(this::profileActionPerformed);

        logout.setText("Logout");
        logout.setBackgroundColor(new java.awt.Color(0, 0, 153));
        logout.setBorderColor(new java.awt.Color(0, 0, 153));
        logout.setCornerRadius(10);
        logout.setDefaultForeground(new java.awt.Color(255, 255, 255));
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mycourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mycourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        fancyLabel1.setText("profile");
        fancyLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N

        fancyLabel3.setText("Your student and program information.");
        fancyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fancyPanel3.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setBorderThickness(2.0F);
        fancyPanel3.setGradientEnabled(false);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        fancyPanel4.setCornerRadius(360);
        fancyPanel4.setGradientEnd(new java.awt.Color(0, 102, 255));
        fancyPanel4.setGradientStart(new java.awt.Color(51, 153, 255));

        fancyLabel4.setText("ST");
        fancyLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        fancyLabel5.setText("Student");
        fancyLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        fancyLabel6.setText("BSIT · 2nd Year · Section IT-201");

        fancyPanel15.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel15.setBorderEnabled(true);
        fancyPanel15.setCornerRadius(7);
        fancyPanel15.setGradientEnabled(false);
        fancyPanel15.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel15.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel15.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel15.setSolidBackgroundEnabled(true);

        fancyLabel7.setText("PROGRAM");

        fancyLabel13.setText("BS Information Technology");

        javax.swing.GroupLayout fancyPanel15Layout = new javax.swing.GroupLayout(fancyPanel15);
        fancyPanel15.setLayout(fancyPanel15Layout);
        fancyPanel15Layout.setHorizontalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        fancyPanel15Layout.setVerticalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        fancyPanel21.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel21.setBorderEnabled(true);
        fancyPanel21.setCornerRadius(7);
        fancyPanel21.setGradientEnabled(false);
        fancyPanel21.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel21.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel21.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel21.setSolidBackgroundEnabled(true);

        fancyLabel8.setText("STUDENT NUMBER");

        fancyLabel12.setText("2024-10234");

        javax.swing.GroupLayout fancyPanel21Layout = new javax.swing.GroupLayout(fancyPanel21);
        fancyPanel21.setLayout(fancyPanel21Layout);
        fancyPanel21Layout.setHorizontalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel21Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel21Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel21Layout.setVerticalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        fancyPanel22.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel22.setBorderEnabled(true);
        fancyPanel22.setCornerRadius(7);
        fancyPanel22.setGradientEnabled(false);
        fancyPanel22.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel22.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel22.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel22.setSolidBackgroundEnabled(true);

        fancyLabel9.setText("EMAIL");

        fancyLabel14.setText("Student@bestlink.edu.ph");

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel22Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        fancyPanel24.setBorderColor(new java.awt.Color(204, 204, 204));
        fancyPanel24.setBorderEnabled(true);
        fancyPanel24.setCornerRadius(7);
        fancyPanel24.setGradientEnabled(false);
        fancyPanel24.setGradientEnd(new java.awt.Color(153, 255, 153));
        fancyPanel24.setGradientStart(new java.awt.Color(51, 255, 102));
        fancyPanel24.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel24.setSolidBackgroundEnabled(true);

        fancyLabel11.setText("CURRENT LOAD");

        fancyLabel15.setText("0 / 27 units");

        javax.swing.GroupLayout fancyPanel24Layout = new javax.swing.GroupLayout(fancyPanel24);
        fancyPanel24.setLayout(fancyPanel24Layout);
        fancyPanel24Layout.setHorizontalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel24Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel24Layout.setVerticalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        fancyButton2.setText("AY 2026–2027 · 1st Semester");

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addContainerGap())
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE))))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycoursesActionPerformed
       new MyCourses().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_mycoursesActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
     new Dashboard().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton courses;
    private fancyui.FancyButton dashboard;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel15;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyLabel fancyLabel8;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel15;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel21;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel23;
    private fancyui.FancyPanel fancyPanel24;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private javax.swing.JSeparator jSeparator1;
    private fancyui.FancyButton logout;
    private fancyui.FancyButton mycourses;
    private fancyui.FancyButton profile;
    // End of variables declaration//GEN-END:variables
}
